### ISSUE TITLE
Serve ISCED with Skosmos

### ISSUE THREAD

**Issue by acka47** [hbz/vocabs-edu#6]
You can already find a first try at http://aither.lobid.org/skosmos/en/. @dr0i got Skosmos running for us without major problems (though there were some smaller ones).

There were some problems getting the vocabulary shown in Skosmos, though. You need a SPARQL endpoint for this. It didn't work with 4store so we installed Fuseki. It took me some time to understand the interaction of Fuseki, and Skosmos configuration in `vocabularies.ttl`. (Also, it wasn't as easy as hoped to get the data into Fuseki, the web interface doesn't work like it should.) However, isced-2013 is now browsable in Skosmos, see http://aither.lobid.org.de/skosmos/isced2013/en/. @literarymachine, you can already try it out but keep in mind that some things will still change. To do:
- The "hierarchy" tab isn't shown on the vocabulary page. I don't know why.  Maybe @osma can tell us what  is wrong?
- We haven't claimed and set up the name space at w3id yet, see #5.
- We have to find out how to use Skosmos for serving the concept scheme under its actual name space.

**Comment by osma** [comment]
> The "hierarchy" tab isn't shown on the vocabulary page. I don't know why. Maybe @osma can tell us what is wrong?

Add this to vocabularies.ttl somewhere under :isced2013:

```
skosmos:showTopConcepts true ;
```

That should do the trick. The top level hierarchy isn't shown by default, because many SKOS vocabularies don't have a proper hierarchy.

> We have to find out how to use Skosmos for serving the concept scheme under its actual name space. 

You will need some rewrite rules, for example by using Apache mod_rewrite. So you make Apache redirect (or proxy) the real URLs to the URLs that Skosmos can serve. RDF representations can be had via the API, for example this URL will give you a content-negotiated RDF representation of the concept "Arts and humanities": http://aither.lobid.org/skosmos/rest/v1/isced2013/data?uri=https://w3id.org/oer/isced-2013/n02

However, you will need to do the content negotiation between HTML and RDF in your rewrite rules, Skosmos currently does not do that. (If you need this, create an issue on GitHub)

Oh, and thanks for trying Skosmos! If you need any help, just ask.

**Comment by acka47** [comment]
@osma Thanks for the quick help, I appreciate it very much.
I added the triple and it now works, see http://aither.lobid.org/skosmos/isced2013/en/. Regarding the rewrites we will give it a try next week. Might well be that I ping you again at some point...

**Comment by acka47** [comment]
I also loaded isced-1997 into Skosms, see http://aither.lobid.org/skosmos/isced-1997/en/. It probably doesn't make much sense to load such a small scheme (only seven concepts!) into Skosmos. For consistency's sake I would just do this.

**Comment by acka47** [comment]
Closing this one as we already serve ISCED with Skosmos. For adjustments we'll open new tickets.
